/*========================================================
  TABLA DE CAT_ESTADO_FACTURAS
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ESTADO_FACTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ESTADO_FACTURA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_ESTADO_FACTURA (
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ESTADO_FACTURA PRIMARY KEY (ID_ESTADO_FACTURA),
    CONSTRAINT CK_ESTADO_FACTURA CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_FACTURA IS 'Tabla catálogo de tipo de estado de factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ID_ESTADO_FACTURA IS 'Clave del estado de la factura RL-001';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.NOMBRE IS 'Nombre del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.DESCRIPCION IS 'Descripción del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ESTADO IS '0=Activo, 99=Inactivo';

CREATE SEQUENCE SEQ_ESTADO_FACTURA START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ID_ESTADO_FACTURA_ID
BEFORE INSERT ON CAT_ESTADO_FACTURA
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO_FACTURA IS NULL THEN
        :NEW.ID_ESTADO_FACTURA := 'EFAC' || LPAD(SEQ_ESTADO_FACTURA.NEXTVAL, 3, '0');
    END IF;
END;
/

/*========================================================
  DATOS INICIALES DE CATALOGO_TIPO_TOKEN
========================================================*/
INSERT INTO CAT_ESTADO_FACTURA ( NOMBRE, DESCRIPCION)
VALUES ( 'PAGADA', 'Factura Pagada');;

INSERT INTO CAT_ESTADO_FACTURA ( NOMBRE, DESCRIPCION)
VALUES ( 'CANCELADA', '');

INSERT INTO CAT_ESTADO_FACTURA ( NOMBRE, DESCRIPCION)
VALUES ( 'EN PROCESO', 'Factura en proceso de pago');

COMMIT;

select * from CAT_ESTADO_FACTURA;