/*========================================================
  TABLA DE CAT_STATUS_MENSAJE
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_STATUS_MENSAJE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STATUS_MENSAJE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/



CREATE TABLE CAT_STATUS_MENSAJE(
    ID_STATUS_MENSAJE VARCHAR2(15) NOT NULL,
    NOMBRE_STATUS VARCHAR2(40) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    ESTADO NUMBER(2) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_id_cat_status_menssage PRIMARY KEY (ID_STATUS_MENSAJE)
);

COMMENT ON TABLE CAT_STATUS_MENSAJE IS 'Tabla que contiene los estados de los mensajes de contacto';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ID_STATUS_MENSAJE IS 'Id de estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.NOMBRE_STATUS IS 'Estado del mensaje';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.DESCRIPCION IS 'Descripcion del estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ESTADO IS 'Estado del registro';
COMMIT;

CREATE SEQUENCE SEQ_STATUS_MENSAJE START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_STAUTS_MENSAJE_ID
BEFORE INSERT ON CAT_STATUS_MENSAJE
FOR EACH ROW
BEGIN
    IF :NEW.ID_STATUS_MENSAJE IS NULL THEN
        :NEW.ID_STATUS_MENSAJE := 'CSM-' || LPAD(SEQ_STATUS_MENSAJE.NEXTVAL, 3, '0');
    END IF;
END;

insert INTO CAT_STATUS_MENSAJE ( NOMBRE_STATUS,DESCRIPCION)
VALUES ( 'Recibido', 'Mensaje recibido por el Administrador' );;;

insert INTO CAT_STATUS_MENSAJE (NOMBRE_STATUS, DESCRIPCION)
VALUES ('Leido', 'Mensaje leido por el Administrador' );

insert INTO CAT_STATUS_MENSAJE (NOMBRE_STATUS,DESCRIPCION)
VALUES ( 'Contestado', 'Mensaje contestado por el Administrador' );;
COMMIT;

