/*========================================================
  TABLA DE CAT_ROLES
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ROL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ROL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_ROL (
    ID_ROL VARCHAR2(10) NOT NULL,
    NOMBRE_ROL VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT CK_ROL_ESTADO CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_ROL IS 'Tabla catálogo de roles';
COMMENT ON COLUMN CAT_ROL.ID_ROL IS 'Clave del rol ejemplo RL-001';
COMMENT ON COLUMN CAT_ROL.NOMBRE_ROL IS 'Nombre del rol';
COMMENT ON COLUMN CAT_ROL.DESCRIPCION IS 'Descripción del rol';
COMMENT ON COLUMN CAT_ROL.ESTADO IS '0=Activo, 99=Inactivo';

CREATE SEQUENCE SEQ_ROL START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ROL_ID
BEFORE INSERT ON CAT_ROL
FOR EACH ROW
BEGIN
    IF :NEW.ID_ROL IS NULL THEN
        :NEW.ID_ROL := 'RL-' || LPAD(SEQ_ROL.NEXTVAL, 3, '0');
    END IF;
END;
/

/*========================================================
  DATOS INICIALES DE ROLES
========================================================*/
INSERT INTO CAT_ROL ( NOMBRE_ROL, DESCRIPCION)
VALUES ( 'ADMIN', 'Administrador del sistema');

INSERT INTO CAT_ROL ( NOMBRE_ROL, DESCRIPCION)
VALUES ( 'USER', 'Usuario estándar');

COMMIT;

select * from CAT_ROL;










