-- ===========================
--  DDL CAT_TIPO_CLIENTE
-- ===========================

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_CLIENTE_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE CAT_TIPO_CLIENTE (
    ID_TIPO_CLIENTE VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TIPO_CLIENTE PRIMARY KEY (ID_TIPO_CLIENTE),
    CONSTRAINT CK_TIPO_CLIENTE CHECK (ESTADO IN (0, 99))

);

COMMENT ON TABLE CAT_TIPO_CLIENTE IS 'Tabla catálogo de tipo de estado de factura';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ID_TIPO_CLIENTE IS 'Clave del estado de la factura RL-001';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOMBRE IS 'Nombre del estado de la factura';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.DESCRIPCION IS 'Descripción del estado de la factura';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ESTADO IS '0=Activo, 99=Inactivo';

CREATE SEQUENCE SEQ_TIPO_CLIENTE_ID START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ID_TIPO_CLIENTE
BEFORE INSERT ON CAT_TIPO_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_CLIENTE IS NULL THEN
        :NEW.ID_TIPO_CLIENTE := 'TCLI' || LPAD(SEQ_TIPO_CLIENTE_ID.NEXTVAL, 3, '0');
    END IF;
END;
/

/*========================================================
  DATOS INICIALES DE CATALOGO_TIPO_TOKEN
========================================================*/
INSERT INTO CAT_TIPO_CLIENTE ( NOMBRE, DESCRIPCION)
VALUES ( 'MORAL', 'Persona Moral o empresa');;;

INSERT INTO CAT_TIPO_CLIENTE ( NOMBRE, DESCRIPCION)
VALUES ( 'FISICA', 'Persona fisica');

INSERT INTO CAT_TIPO_CLIENTE ( NOMBRE, DESCRIPCION)
VALUES ( 'GENERICO', 'Entidad que no se identifica como persona fisica o moral');;

COMMIT;

