/*========================================================
  TABLA DE CAT_ESTADO_PAGO
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ESTADO_PAGO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ESTADO_PAGO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE CAT_ESTADO_PAGO (
    ID_ESTADO_PAGO VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ESTADO_PAGO PRIMARY KEY (ID_ESTADO_PAGO),
    CONSTRAINT CK_ESTADO_PAGO CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_PAGO IS 'Tabla catálogo de tipo de estado de factura';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ID_ESTADO_PAGO IS 'Clave del estado de la factura RL-001';
COMMENT ON COLUMN CAT_ESTADO_PAGO.NOMBRE IS 'Nombre del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_PAGO.DESCRIPCION IS 'Descripción del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ESTADO IS '0=Activo, 99=Inactivo';

CREATE SEQUENCE SEQ_ESTADO_PAGO START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ID_ESTADO_PAGO
BEFORE INSERT ON CAT_ESTADO_PAGO
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO_PAGO IS NULL THEN
        :NEW.ID_ESTADO_PAGO := 'EFAC' || LPAD(SEQ_ESTADO_PAGO.NEXTVAL, 3, '0');
    END IF;
END;
/

/*========================================================
  DATOS INICIALES DE CATALOGO_TIPO_TOKEN
========================================================*/
INSERT INTO CAT_ESTADO_PAGO ( NOMBRE, DESCRIPCION)
VALUES ( 'PROCESADO', 'PAGO PROCESADO CON EXITO');;;

INSERT INTO CAT_ESTADO_PAGO ( NOMBRE, DESCRIPCION)
VALUES ( 'CANCELADO', 'Pago cancelado por el cliente');;

INSERT INTO CAT_ESTADO_PAGO ( NOMBRE, DESCRIPCION)
VALUES ( 'EN PROCESO', 'Pago en proceso de pago');

COMMIT;

