/*========================================================
  TABLA DE CAT_TIPO_TOKEN
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_TOKEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_TOKEN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_TIPO_TOKEN (
    ID_TIPO_TOKEN VARCHAR2(15) NOT NULL,
    NOMBRE_TOKEN VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TIPO_TOKEN PRIMARY KEY (ID_TIPO_TOKEN),
    CONSTRAINT CK_ESTADO_TOKEN CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_TOKEN IS 'Tabla catálogo de tipo de token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ID_TIPO_TOKEN IS 'Clave del tipo del token RL-001';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOMBRE_TOKEN IS 'Nombre del token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.DESCRIPCION IS 'Descripción del token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ESTADO IS '0=Activo, 99=Inactivo';

CREATE SEQUENCE SEQ_TIPO_TOKEN START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TIPO_TOKEN_ID
BEFORE INSERT ON CAT_TIPO_TOKEN
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_TOKEN IS NULL THEN
        :NEW.ID_TIPO_TOKEN := 'CTK-' || LPAD(SEQ_TIPO_TOKEN.NEXTVAL, 3, '0');
    END IF;
END;
/

/*========================================================
  DATOS INICIALES DE CATALOGO_TIPO_TOKEN
========================================================*/
INSERT INTO CAT_TIPO_TOKEN ( NOMBRE_TOKEN, DESCRIPCION)
VALUES ( 'EMAIL_VERIFY', 'Verificar Perfil de Usuario');

INSERT INTO CAT_TIPO_TOKEN ( NOMBRE_TOKEN, DESCRIPCION)
VALUES ( 'RESET_PASSWORD', 'Cambio de Password');

INSERT INTO CAT_TIPO_TOKEN ( NOMBRE_TOKEN, DESCRIPCION)
VALUES ( 'REACTIVACION', 'Reactivar Cuenta');

COMMIT;

Select * from CAT_TIPO_TOKEN;

