-- ===========================
--  DDL FACTURAS Y BITÁCORA
-- ===========================

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FACTURAS_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FACTURA_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FACTURAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FACTURAS (
    ID_FACTURA VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    MONTO_TOTAL NUMBER(10,2) NOT NULL,
    FOLIO NUMBER NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    FECHA_FACTURA DATE DEFAULT SYSDATE,

    CONSTRAINT PK_ID_FACTURA_FACTURAS PRIMARY KEY (ID_FACTURA),
    CONSTRAINT FK_ID_CLIENTE_FACTURAS FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
    CONSTRAINT FK_ID_ESTADO_FACTURAS FOREIGN KEY (ID_ESTADO_FACTURA) REFERENCES CAT_ESTADO_FACTURA (ID_ESTADO_FACTURA)
);

COMMENT ON TABLE FACTURAS IS 'Tabla que contiene las facturas de los clientes';
COMMENT ON COLUMN FACTURAS.ID_FACTURA IS 'Llave primaria de la tabla FACTURAS';
COMMENT ON COLUMN FACTURAS.ID_CLIENTE IS 'Llave foránea del cliente';
COMMENT ON COLUMN FACTURAS.MONTO_TOTAL IS 'Monto total de la factura';
COMMENT ON COLUMN FACTURAS.FOLIO IS 'Folio consecutivo por año';
COMMENT ON COLUMN FACTURAS.ANIO IS 'Año de la factura';
COMMENT ON COLUMN FACTURAS.ID_ESTADO_FACTURA IS 'Id estado factura';
COMMENT ON COLUMN FACTURAS.FECHA_FACTURA IS 'Fecha de la factura';

CREATE SEQUENCE SEQ_FACTURA_ID
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999 NOCACHE CYCLE;

CREATE OR REPLACE TRIGGER TRG_FACTURA_ID
BEFORE INSERT ON FACTURAS
FOR EACH ROW
BEGIN
    IF :NEW.ID_FACTURA IS NULL THEN
        :NEW.ID_FACTURA := 'FAC-' || :NEW.ANIO || LPAD(SEQ_FACTURA_ID.NEXTVAL, 3, '0');
    END IF;
END;


CREATE TABLE FACTURAS_BIT (
    ID_FACTURA_BIT VARCHAR2(36) NOT NULL,
    ID_FACTURA VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    MONTO_TOTAL NUMBER(10,2) NOT NULL,
    FOLIO NUMBER NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    FECHA_FACTURA DATE,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_ID_FACTURA_BIT PRIMARY KEY (ID_FACTURA_BIT)
);

COMMENT ON TABLE FACTURAS_BIT IS 'Bitácora de facturas';
COMMENT ON COLUMN FACTURAS_BIT.ID_FACTURA_BIT IS 'Id de bitácora';
COMMENT ON COLUMN FACTURAS_BIT.ID_FACTURA IS 'Id de factura';
COMMENT ON COLUMN FACTURAS_BIT.ID_CLIENTE IS 'Id del cliente';
COMMENT ON COLUMN FACTURAS_BIT.MONTO_TOTAL IS 'Monto total';
COMMENT ON COLUMN FACTURAS_BIT.FOLIO IS 'Folio';
COMMENT ON COLUMN FACTURAS_BIT.ANIO IS 'Año';
COMMENT ON COLUMN FACTURAS_BIT.ID_ESTADO_FACTURA IS 'Id estado factura';
COMMENT ON COLUMN FACTURAS_BIT.FECHA_FACTURA IS 'Fecha factura';
COMMENT ON COLUMN FACTURAS_BIT.FECHA_CREACION IS 'Fecha creación';
COMMENT ON COLUMN FACTURAS_BIT.FECHA_MODIFICACION IS 'Fecha modificación';
COMMENT ON COLUMN FACTURAS_BIT.ACCION IS 'Acción';
COMMENT ON COLUMN FACTURAS_BIT.IP IS 'IP origen';

CREATE OR REPLACE TRIGGER TRG_FACTURAS_AUD
AFTER INSERT OR UPDATE ON FACTURAS
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_CREACION := :OLD.FECHA_FACTURA;
        V_FECHA_MODIFICACION := SYSDATE;
    END IF;

    INSERT INTO FACTURAS_BIT (
        ID_FACTURA_BIT,
        ID_FACTURA,
        ID_CLIENTE,
        MONTO_TOTAL,
        FOLIO,
        ANIO,
        ID_ESTADO_FACTURA,
        FECHA_FACTURA,
        FECHA_CREACION,
        FECHA_MODIFICACION,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_FACTURA,
        :NEW.ID_CLIENTE,
        :NEW.MONTO_TOTAL,
        :NEW.FOLIO,
        :NEW.ANIO,
        :NEW.ID_ESTADO_FACTURA,
        :NEW.FECHA_FACTURA,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );

END;
/