/*========================================================
  TABLA DE MENSAJE_CONTACTO
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MENSAJE_CONTACTO_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MENSAJE_CONTACTO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MENSAJE_CONTACTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE MENSAJE_CONTACTO (
    ID_MENSAJE VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    CORREO VARCHAR2(60) NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
    FECHA_ENVIO DATE DEFAULT SYSDATE,
    ID_STATUS_MENSAJE VARCHAR2(15) DEFAULT 'CSM-000' NOT NULL,
    USUARIO_RESPUESTA VARCHAR2(1000) DEFAULT 'NINGUNO' NOT NULL,

    CONSTRAINT PK_ID_MENSAJE PRIMARY KEY (ID_MENSAJE),

    CONSTRAINT FK_ID_ESTATUS_MENSAJE
        FOREIGN KEY (ID_STATUS_MENSAJE)
        REFERENCES CAT_STATUS_MENSAJE (ID_STATUS_MENSAJE)
);



COMMENT ON TABLE MENSAJE_CONTACTO IS 'Tabla que contiene los mensajes de contacto';
COMMENT ON COLUMN MENSAJE_CONTACTO.ID_MENSAJE IS 'Id de mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.NOMBRE IS 'Nombre del usuario';
COMMENT ON COLUMN MENSAJE_CONTACTO.CORREO IS 'Correo del usuario';
COMMENT ON COLUMN MENSAJE_CONTACTO.DESCRIPCION IS 'Descripción del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.ACTIVO IS 'Bandera de activo';
COMMENT ON COLUMN MENSAJE_CONTACTO.FECHA_ENVIO IS 'Fecha de envío del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.ID_STATUS_MENSAJE IS 'Estado del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.USUARIO_RESPUESTA IS 'Usuario que responde';

COMMIT;

CREATE SEQUENCE SEQ_MENSAJE_CONTACTO START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_MENSAJE_CONTACTO_ID
BEFORE INSERT ON MENSAJE_CONTACTO
FOR EACH ROW
BEGIN
    IF :NEW.ID_MENSAJE IS NULL THEN
        :NEW.ID_MENSAJE := 'CTK-' || LPAD(SEQ_MENSAJE_CONTACTO.NEXTVAL, 3, '0');
    END IF;
END;
/


CREATE TABLE MENSAJE_CONTACTO_BIT (
    ID_BITACORA VARCHAR2(36) NOT NULL,
    ID_MENSAJE VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    CORREO VARCHAR2(60) NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    ACTIVO NUMBER(1) NOT NULL,
    FECHA_ENVIO DATE,
    ID_STATUS_MENSAJE VARCHAR2(15) NOT NULL,
    USUARIO_RESPUESTA VARCHAR2(1000) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_ID_BITACORA PRIMARY KEY (ID_BITACORA)

);

COMMENT ON TABLE MENSAJE_CONTACTO_BIT IS 'Bitácora de mensajes de contacto';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.ID_BITACORA IS 'Identificador de la tabla mensajes bitacora';
COMMENT on column MENSAJE_CONTACTO_BIT.ID_MENSAJE is 'Identificador del mensaje';
COMMENT on column MENSAJE_CONTACTO_BIT.NOMBRE is 'Nombre del usuario';
COMMENT on column MENSAJE_CONTACTO_BIT.CORREO is 'Correo del usuario';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.DESCRIPCION IS 'Descripcion del mensaje';
COMMENT ON COLUMN MEnSAJE_CONTACTO_BIT.ACTIVO IS 'Bandera de activo';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.FECHA_ENVIO IS 'Fecha en que se envio';
COMMENT ON COLUMN MEnSAJE_CONTACTO_BIT.ID_STATUS_MENSAJE IS 'Estado del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.USUARIO_RESPUESTA IS 'Usuario que responde';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.FECHA_CREACION IS 'Fecha de creacion';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.FECHA_MODIFICACION IS 'Fecha modificacion';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.ACCION IS 'Accion realizada';
COMMENT ON COLUMN MENSAJE_CONTACTO_BIT.IP IS 'Ip del usuario que realizo la accion';


COMMIT;

CREATE OR REPLACE TRIGGER TRG_MENSAJE_CONTACTO_AUD
AFTER INSERT OR UPDATE ON MENSAJE_CONTACTO
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ENVIO;

        IF :OLD.ID_STATUS_MENSAJE = 'CSM-000' AND :NEW.ID_STATUS_MENSAJE = 'CSM-001' THEN
            V_ACCION := 'LEIDO';

        ELSIF :OLD.ID_STATUS_MENSAJE = 'CSM-001' AND :NEW.ID_STATUS_MENSAJE = 'CSM-002' THEN
            V_ACCION := 'RESPONDIDO';

        ELSIF :OLD.ID_STATUS_MENSAJE = 'CSM-000' AND :NEW.ID_STATUS_MENSAJE = 'CSM-002' THEN
            V_ACCION := 'RESPONDIDO';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO MENSAJE_CONTACTO_BIT (
        ID_BITACORA,
        ID_MENSAJE,
        NOMBRE,
        CORREO,
        DESCRIPCION,
        ACTIVO,
        FECHA_ENVIO,
        ID_STATUS_MENSAJE,
        USUARIO_RESPUESTA,
        FECHA_CREACION,
        FECHA_MODIFICACION,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_MENSAJE,
        :NEW.NOMBRE,
        :NEW.CORREO,
        :NEW.DESCRIPCION,
        :NEW.ACTIVO,
        :NEW.FECHA_ENVIO,
        :NEW.ID_STATUS_MENSAJE,
        :NEW.USUARIO_RESPUESTA,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );
END;
/


select * from MENSAJE_CONTACTO;

select * from CAT_STATUS_MENSAJE;

