-- ===========================
--  DDL PAGOS Y BITÁCORA
-- ===========================

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAGOS_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAGO_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAGOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PAGOS (
  ID_PAGO VARCHAR2(36) NOT NULL,
  ID_FACTURA VARCHAR2(36) NOT NULL,
  MONTO NUMBER (10,2) NOT NULL,
  ID_ESTADO_PAGO VARCHAR2(15) NOT NULL,
  FECHA_PAGO DATE DEFAULT SYSDATE,
  CONSTRAINT pk_id_pago_pagos PRIMARY KEY (ID_PAGO),
  CONSTRAINT fk_id_factura_pagos FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS (ID_FACTURA),
  CONSTRAINT fk_id_estado_pago FOREIGN KEY (ID_ESTADO_PAGO) REFERENCES CAT_ESTADO_PAGO (ID_ESTADO_PAGO)
);
COMMENT ON TABLE PAGOS IS 'Tabla que contiene los Pagos Totales o Parciales de una Factura';
COMMENT ON COLUMN PAGOS.ID_PAGO IS 'Llave primaria de la tabla PAGOS';
COMMENT ON COLUMN PAGOS.ID_FACTURA IS 'Llave foranea ID_FACTURA que hace referencia a la tabla FACTURAS';
COMMENT ON COLUMN PAGOS.MONTO IS 'Monto del Pago de la Factura';
COMMENT ON COLUMN PAGOS.ID_ESTADO_PAGO IS 'ID del Estado del Pago de la Factura';
COMMENT ON COLUMN PAGOS.FECHA_PAGO IS 'Fecha de Pago de la Factura';

CREATE SEQUENCE SEQ_PAGO_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999 NOCACHE CYCLE;

CREATE OR REPLACE TRIGGER TRG_PAGO_ID
BEFORE INSERT ON PAGOS
FOR EACH ROW
BEGIN
    IF :NEW.ID_PAGO IS NULL THEN
        :NEW.ID_PAGO := 'PAG-' || :NEW.FECHA_PAGO || LPAD(SEQ_PAGO_ID.NEXTVAL, 3, '0');
    END IF;
END;
/

CREATE TABLE PAGOS_BIT (
    ID_PAGO_BIT VARCHAR2(36) NOT NULL,
    ID_PAGO VARCHAR2(36) NOT NULL,
    ID_FACTURA VARCHAR2(36) NOT NULL,
    MONTO NUMBER(10,2) NOT NULL,
    ID_ESTADO_PAGO VARCHAR2(15) NOT NULL,
    FECHA_PAGO DATE,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_ID_PAGO_BIT PRIMARY KEY (ID_PAGO_BIT)
);

COMMENT ON TABLE PAGOS_BIT IS 'Bitácora de pagos';
COMMENT ON COLUMN PAGOS_BIT.ID_PAGO_BIT IS 'Id de bitácora';
COMMENT ON COLUMN PAGOS_BIT.ID_PAGO IS 'Id del pago';
COMMENT ON COLUMN PAGOS_BIT.ID_FACTURA IS 'Id de factura';
COMMENT ON COLUMN PAGOS_BIT.MONTO IS 'Monto del pago';
COMMENT ON COLUMN PAGOS_BIT.ID_ESTADO_PAGO IS 'Id del estado del pago';
COMMENT ON COLUMN PAGOS_BIT.FECHA_PAGO IS 'Fecha del pago';
COMMENT ON COLUMN PAGOS_BIT.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN PAGOS_BIT.FECHA_MODIFICACION IS 'Fecha de modificación';
COMMENT ON COLUMN PAGOS_BIT.ACCION IS 'Acción realizada';
COMMENT ON COLUMN PAGOS_BIT.IP IS 'IP origen';

CREATE OR REPLACE TRIGGER TRG_PAGOS_AUD
AFTER INSERT OR UPDATE ON PAGOS
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_CREACION := :OLD.FECHA_PAGO;
        V_FECHA_MODIFICACION := SYSDATE;
    END IF;

    INSERT INTO PAGOS_BIT (
        ID_PAGO_BIT,
        ID_PAGO,
        ID_FACTURA,
        MONTO,
        ID_ESTADO_PAGO,
        FECHA_PAGO,
        FECHA_CREACION,
        FECHA_MODIFICACION,
        ACCION,
        IP
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_PAGO,
        :NEW.ID_FACTURA,
        :NEW.MONTO,
        :NEW.ID_ESTADO_PAGO,
        :NEW.FECHA_PAGO,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );

END;
/

