/*========================================================
  TABLA PERSONA
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PERSONA_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERSONA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PERSONA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PERSONA (
    ID_PERSONA VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    APATERNO VARCHAR2(100) NOT NULL,
    AMATERNO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100) NOT NULL,
    UUID_CIUDAD VARCHAR2(36)  NOT NULL,
    UUID_ESTADO VARCHAR2(36) NOT NULL,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_ALTA DATE DEFAULT SYSDATE,
    VERIFICADO NUMBER(2) DEFAULT 99 NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA),
    CONSTRAINT UK_PERSONA_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_CAT_PERSONA_ESTADO FOREIGN KEY (UUID_ESTADO)
    REFERENCES CAT_ESTADO(UUID_ESTADO),
    CONSTRAINT FK_CAT_PERSONA_CIUDAD FOREIGN KEY (UUID_CIUDAD)
    REFERENCES CAT_CIUDAD(UUID_CIUDAD),
    CONSTRAINT CK_PERSONA_ESTADO CHECK (ESTADO IN (0, 99)),
    CONSTRAINT CK_PERSONA_VERIFICADO CHECK (VERIFICADO IN (0, 99))
);

COMMENT ON TABLE PERSONA IS 'Tabla que almacena información personal';
COMMENT ON COLUMN PERSONA.ID_PERSONA IS 'Id único de persona';
COMMENT ON COLUMN PERSONA.NOMBRE IS 'Nombre completo';
COMMENT ON COLUMN PERSONA.APATERNO IS 'Apellido paterno';
COMMENT ON COLUMN PERSONA.AMATERNO IS 'Apellido materno';
COMMENT ON COLUMN PERSONA.TELEFONO IS 'Número telefónico';
COMMENT ON COLUMN PERSONA.CORREO IS 'Correo electrónico para login';
COMMENT ON COLUMN PERSONA.UUID_CIUDAD IS 'Id de la ciudad';
COMMENT ON COLUMN PERSONA.UUID_ESTADO IS 'Id del estado';
COMMENT ON COLUMN PERSONA.ESTADO IS '0=Activo, 99=Inactivo';
COMMENT ON COLUMN PERSONA.FECHA_ALTA IS 'Fecha de alta';
COMMENT ON COLUMN PERSONA.VERIFICADO IS '0=No verificado, 99=Verificado';

CREATE SEQUENCE SEQ_PERSONA START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_PERSONA_ID
BEFORE INSERT ON PERSONA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PERSONA IS NULL THEN
        :NEW.ID_PERSONA := 'PER-' || LPAD(SEQ_PERSONA.NEXTVAL, 6, '0');
    END IF;
END;

CREATE TABLE PERSONA_BIT (
    ID_PERSONA_BIT VARCHAR2(36) NOT NULL,
    ID_PERSONA VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    APATERNO VARCHAR2(100) NOT NULL,
    AMATERNO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100) NOT NULL,
    UUID_CIUDAD VARCHAR2(36)  NOT NULL,
    UUID_ESTADO VARCHAR2(36) NOT NULL,
    ESTADO NUMBER(2) NOT NULL,
    FECHA_ALTA DATE DEFAULT SYSDATE,
    VERIFICADO NUMBER(2) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ID_PERSONA_BIT_PERSONA_BIT PRIMARY KEY (ID_PERSONA_BIT)

);

COMMENT ON TABLE PERSONA_BIT IS 'Tabla bitacora que almacena información personal';
COMMENT ON COLUMN PERSONA_BIT.ID_PERSONA_BIT IS 'UUID de la bitacora persona';
COMMENT ON COLUMN PERSONA_BIT.ID_PERSONA IS 'Id único de persona';
COMMENT ON COLUMN PERSONA_BIT.NOMBRE IS 'Nombre completo';
COMMENT ON COLUMN PERSONA_BIT.APATERNO IS 'Apellido paterno';
COMMENT ON COLUMN PERSONA_BIT.AMATERNO IS 'Apellido materno';
COMMENT ON COLUMN PERSONA_BIT.TELEFONO IS 'Número telefónico';
COMMENT ON COLUMN PERSONA_BIT.CORREO IS 'Correo electrónico para login';
COMMENT ON COLUMN PERSONA_BIT.UUID_CIUDAD IS 'Id de la ciudad';
COMMENT ON COLUMN PERSONA_BIT.UUID_ESTADO IS 'Id del estado';
COMMENT ON COLUMN PERSONA_BIT.ESTADO IS '0=Activo, 99=Inactivo';
COMMENT ON COLUMN PERSONA_BIT.FECHA_ALTA IS 'Fecha de alta';
COMMENT ON COLUMN PERSONA_BIT.VERIFICADO IS '0=No verificado, 99=Verificado';
COMMENT ON COLUMN PERSONA_BIT.FECHA_CREACION IS 'Fecha de creacion del registo';
COMMENT ON COLUMN PERSONA_BIT.FECHA_MODIFICACION IS 'Fecha de modificacion del registo';
COMMENT ON COLUMN PERSONA_BIT.ACCION IS 'Accion realizada';
COMMENT ON COLUMN PERSONA_BIT.IP IS 'Ip del usuario que realizo la accion';



CREATE OR REPLACE TRIGGER TRG_PERSONA_AUD
AFTER INSERT OR UPDATE ON PERSONA
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;
        -- Detectar borrado lógico
        IF :OLD.ESTADO = 0 AND :NEW.ESTADO = 99 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 99 AND :NEW.ESTADO =0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.VERIFICADO = 99 AND :NEW.VERIFICADO =0 THEN
            V_ACCION := 'VERIFIED';
        ELSIF :OLD.VERIFICADO = 0 AND :NEW.VERIFICADO =99 THEN
            V_ACCION := 'UNVERIFIED';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO PERSONA_BIT ( ID_PERSONA_BIT, ID_PERSONA, NOMBRE, APATERNO, AMATERNO, TELEFONO, CORREO, UUID_CIUDAD, UUID_ESTADO,
                              ESTADO, FECHA_ALTA , VERIFICADO , FECHA_CREACION , FECHA_MODIFICACION, ACCION, IP )
    VALUES (
        SYS_GUID(),
        :NEW.ID_PERSONA,
        :NEW.NOMBRE,
        :NEW.APATERNO,
        :NEW.AMATERNO,
        :NEW.TELEFONO,
        :NEW.CORREO,
        :NEW.UUID_CIUDAD,
        :NEW.UUID_ESTADO,
        :NEW.ESTADO,
        :NEW.FECHA_ALTA,
        :NEW.VERIFICADO,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );

END;


insert into PERSONA(nombre, apaterno, amaterno, telefono, correo, uuid_ciudad, uuid_estado, estado, fecha_alta, verificado)
values ('Oscar Eduardo','Sanchez','Gonzalez','4731295482','oscar.e.sanchez.qa@gmail.com', '006e25aa-7c30-4c1c-9770-6c91055494bb','838fd385-c34a-46b1-bd3d-cb119a086aa0',0, SYSDATE, 0);

insert into PERSONA(nombre, apaterno, amaterno, telefono, correo, uuid_ciudad, uuid_estado, estado, fecha_alta, verificado)
values ('Oscar Eduardo','Sanchez','Gonzalez','4731295482','oscar.e.sanchez.prod@gmail.com', '006e25aa-7c30-4c1c-9770-6c91055494bb','838fd385-c34a-46b1-bd3d-cb119a086aa0',0, SYSDATE, 0);

commit;