/*========================================================
  TABLA DE TELEFONOS
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TELEFONOS_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TELEFONO_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TELEFONOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE TELEFONOS (
  ID_TELEFONO VARCHAR2(36) NOT NULL,
  ID_CLIENTE VARCHAR2(36) NOT NULL,
  TELEFONO VARCHAR2(15) NOT NULL,
  ESTADO NUMBER(1) NOT NULL,
  FECHA_ALTA DATE DEFAULT SYSDATE,
  CONSTRAINT pk_id_telefono_telefonos PRIMARY KEY (ID_TELEFONO),
  CONSTRAINT fk_id_cliente_telefonos FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);
COMMENT ON TABLE TELEFONOS IS 'Tabla que contiene los Teléfonos de los Clientes';
COMMENT ON COLUMN TELEFONOS.ID_TELEFONO IS 'Llave primaria de la tabla TELEFONOS';
COMMENT ON COLUMN TELEFONOS.ID_CLIENTE IS 'Llave foranea ID_CLIENTE que hace referencia a la tabla CLIENTES';
COMMENT ON COLUMN TELEFONOS.TELEFONO IS 'Número Teléfonico del Cliente';
COMMENT ON COLUMN TELEFONOS.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN TELEFONOS.FECHA_ALTA IS 'Campo de control que indica la Fecha de Alta en la BD';


CREATE SEQUENCE SEQ_TELEFONO_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TELEFONO_ID
BEFORE INSERT ON TELEFONOS
FOR EACH ROW
BEGIN
    IF :NEW.ID_TELEFONO IS NULL THEN
       :NEW.ID_TELEFONO := 'TEL-' || LPAD(SEQ_TELEFONO_ID.NEXTVAL, 6, '0');
    END IF;
END;

-- Creación de la tabla de Bitácota de TELEFONOS
CREATE TABLE TELEFONOS_BIT (
  ID_TELEFONO_BIT VARCHAR2(36) NOT NULL,
  ID_TELEFONO VARCHAR2(36) NOT NULL,
  ID_CLIENTE VARCHAR2(36) NOT NULL,
  TELEFONO VARCHAR2(15) NOT NULL,
  ESTADO NUMBER(1) NOT NULL,
  FECHA_ALTA DATE DEFAULT SYSDATE,
  FECHA_CREACION DATE DEFAULT SYSDATE,
  FECHA_MODIFICACION DATE,
  ACCION VARCHAR2(10) NOT NULL,
  IP VARCHAR2(30) NOT NULL,
  CONSTRAINT pk_id_telefono_bit_telefonos_bit PRIMARY KEY (ID_TELEFONO_BIT)

);
COMMENT ON TABLE TELEFONOS_BIT IS 'Tabla de Bitácora que contiene los Teléfonos de los Clientes';
COMMENT ON COLUMN TELEFONOS_BIT.ID_TELEFONO_BIT IS 'Llave primaria de la tabla TELEFONOS_BIT';
COMMENT ON COLUMN TELEFONOS_BIT.ID_TELEFONO IS 'Llave foranea ID_TELEFONO que hace referencia a la tabla TELEFONOS';
COMMENT ON COLUMN TELEFONOS_BIT.ID_CLIENTE IS 'Llave foranea ID_CLIENTE que hace referencia a la tabla CLIENTES';
COMMENT ON COLUMN TELEFONOS_BIT.TELEFONO IS 'Número Teléfonico del Cliente';
COMMENT ON COLUMN TELEFONOS_BIT.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN TELEFONOS_BIT.FECHA_ALTA IS 'Campo de control que indica la Fecha de Alta en la BD';
COMMENT ON COLUMN TELEFONOS_BIT.FECHA_CREACION IS 'Campo de control que indica la Fecha de Creación en la BD';
COMMENT ON COLUMN TELEFONOS_BIT.FECHA_MODIFICACION IS 'Campo de control que indica la Fecha de Modifcación en la BD';
COMMENT ON COLUMN TELEFONOS_BIT.ACCION IS 'Campo de control que indica la Acción en el Registro';
COMMENT ON COLUMN TELEFONOS_BIT.IP IS 'Campo de control que indica IP de donde se solicito operación en el Registro';

-- ===========================
--  Trigger Auditoria clientes
-- ===========================

CREATE OR REPLACE TRIGGER TRG_TELEFONO_AUD
AFTER INSERT OR UPDATE ON TELEFONOS
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;
        -- Detectar borrado lógico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO =1 THEN
            V_ACCION := 'ACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO TELEFONOS_BIT ( ID_TELEFONO_BIT, ID_TELEFONO, ID_CLIENTE, TELEFONO, ESTADO, FECHA_ALTA, FECHA_CREACION
        , FECHA_MODIFICACION, ACCION, IP )
    VALUES (
        SYS_GUID(),
        :NEW.ID_TELEFONO,
        :NEW.ID_CLIENTE,
        :NEW.TELEFONO,
        :NEW.ESTADO,
        :NEW.FECHA_ALTA,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );

END;

