/*========================================================
  TABLA DE TOKEN_VERIFICACION
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TOKEN_VERIFICACION_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TOKEN_VERIFICACION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TOKEN_VERIFICACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE TOKEN_VERIFICACION (
    ID_TOKEN_VERIFICACION VARCHAR2(20) NOT NULL,
    ID_PERSONA VARCHAR2(36) NOT NULL,
    TOKEN VARCHAR2(255) NOT NULL,
    ID_TIPO_TOKEN VARCHAR2(20) NOT NULL,
    USADO NUMBER(1) DEFAULT 0 NOT NULL,
    CADUCADO NUMBER(1) DEFAULT 0 NOT NULL,
    FECHA_ALTA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    FECHA_USO TIMESTAMP,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    NOTAS VARCHAR2(100),

    CONSTRAINT PK_TOKEN_VERIFICACION PRIMARY KEY (ID_TOKEN_VERIFICACION),

    CONSTRAINT FK_TOKENV_USUARIO
        FOREIGN KEY (ID_PERSONA)
        REFERENCES PERSONA(ID_PERSONA),

    CONSTRAINT FK_TIPO_TOKENV
        FOREIGN KEY (ID_TIPO_TOKEN)
        REFERENCES CAT_TIPO_TOKEN(ID_TIPO_TOKEN),

    CONSTRAINT UK_TOKEN UNIQUE (TOKEN),

    CONSTRAINT CK_TOKEN_USADO CHECK (USADO IN (0,1)),
    CONSTRAINT CK_TOKEN_CADUCADO CHECK (CADUCADO IN (0,1))
);

COMMENT ON TABLE TOKEN_VERIFICACION IS 'Tabla catálogo de tipo de token';
COMMENT ON COLUMN TOKEN_VERIFICACION.ID_TOKEN_VERIFICACION IS 'Clave del token verificacion';
COMMENT ON COLUMN TOKEN_VERIFICACION.ID_PERSONA IS 'Clave de la persona';
COMMENT ON COLUMN TOKEN_VERIFICACION.TOKEN IS 'Token de verificacion';
COMMENT ON COLUMN TOKEN_VERIFICACION.ID_TIPO_TOKEN IS 'Id Tipo de token';
COMMENT ON COLUMN TOKEN_VERIFICACION.USADO IS 'Indica si el token ya fue usado';
COMMENT ON COLUMN TOKEN_VERIFICACION.CADUCADO IS 'Indica si el token ya fue caducado';
COMMENT ON COLUMN TOKEN_VERIFICACION.FECHA_ALTA IS 'Fecha de creacion del token';
COMMENT ON COLUMN TOKEN_VERIFICACION.FECHA_EXPIRACION IS 'Fecha de expiracion del token';
COMMENT ON COLUMN TOKEN_VERIFICACION.FECHA_USO IS 'Fecha de uso del token';
COMMENT ON COLUMN TOKEN_VERIFICACION.NOTAS IS 'Notas del token';

CREATE SEQUENCE SEQ_TOKEN_VERIFICACION START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TOKEN_VERIFICACION_ID
BEFORE INSERT ON TOKEN_VERIFICACION
FOR EACH ROW
BEGIN
    IF :NEW.ID_TOKEN_VERIFICACION IS NULL THEN
        :NEW.ID_TOKEN_VERIFICACION := 'TKV-' || LPAD(SEQ_TOKEN_VERIFICACION.NEXTVAL, 9, '0');
    END IF;
END;
/


CREATE TABLE TOKEN_VERIFICACION_BIT (
    ID_TOKEN_VERIFICACION_BIT VARCHAR2(36) NOT NULL,
    ID_TOKEN_VERIFICACION VARCHAR2(20) NOT NULL,
    ID_PERSONA VARCHAR2(36) NOT NULL,
    TOKEN VARCHAR2(255) NOT NULL,
    ID_TIPO_TOKEN VARCHAR2(20) NOT NULL,
    USADO NUMBER(1) DEFAULT 0 NOT NULL,
    CADUCADO NUMBER(1) DEFAULT 0 NOT NULL,
    FECHA_ALTA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    FECHA_USO TIMESTAMP,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    NOTAS VARCHAR2(100),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_TOKEN_VERIFICACION_BIT PRIMARY KEY (ID_TOKEN_VERIFICACION_BIT)
);

COMMENT ON TABLE TOKEN_VERIFICACION_BIT IS 'Tabla catálogo de tipo de token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.ID_TOKEN_VERIFICACION_BIT IS 'Clave del token verificacion en bitacora';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.ID_TOKEN_VERIFICACION IS 'Clave del token verificacion';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.ID_PERSONA IS 'Clave de la persona';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.TOKEN IS 'Token de verificacion';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.ID_TIPO_TOKEN IS 'Id Tipo de token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.USADO IS 'Indica si el token ya fue usado';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.CADUCADO IS 'Indica si el token ya fue caducado';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.FECHA_EXPIRACION IS 'Fecha de expiracion del token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.FECHA_USO IS 'Fecha de uso del token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.NOTAS IS 'Notas del token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.FECHA_CREACION IS 'Fecha de creacion del token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.FECHA_MODIFICACION IS 'Fecha de creacion del token';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.ACCION IS 'Accion realizada';
COMMENT ON COLUMN TOKEN_VERIFICACION_BIT.IP IS 'Ip del usuario';


CREATE OR REPLACE TRIGGER TRG_TOKEN_VERIFICACION_AUD AFTER INSERT OR UPDATE ON TOKEN_VERIFICACION FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;
        -- Detectar borrado lógico
        IF :OLD.ESTADO = 0 AND :NEW.ESTADO = 99 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 99 AND :NEW.ESTADO =0 THEN
            V_ACCION := 'ACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO TOKEN_VERIFICACION_BIT (ID_TOKEN_VERIFICACION_BIT, ID_TOKEN_VERIFICACION, ID_PERSONA, TOKEN, ID_TIPO_TOKEN,
                                        USADO, CADUCADO, FECHA_EXPIRACION,FECHA_USO, ESTADO, NOTAS,
                                        FECHA_CREACION , FECHA_MODIFICACION, ACCION, IP )
    VALUES (
        SYS_GUID(),
        :NEW.ID_TOKEN_VERIFICACION,
        :NEW.ID_PERSONA,
        :NEW.TOKEN,
        :NEW.ID_TIPO_TOKEN,
        :NEW.USADO,
        :NEW.CADUCADO,
        :NEW.FECHA_EXPIRACION,
        :NEW.FECHA_USO,
        :NEW.ESTADO,
        :NEW.NOTAS,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );

END;

insert into token_verificacion (id_persona,  token, ID_TIPO_TOKEN,USADO, caducado, fecha_alta, fecha_expiracion, fecha_uso, estado)
values ('PER-000000', '7256ceb5-4dbc-45c7-9ee8-2d66bb969e08', 'CTK-000', 1,0, SYSDATE, SYSDATE + 1, SYSDATE, 0);

insert into token_verificacion (id_persona,  token, ID_TIPO_TOKEN,USADO, caducado, fecha_alta, fecha_expiracion, fecha_uso, estado)
values ('PER-000001', '7256ceb5-4dbc-45c7-9ee8-3d66bb969e08', 'CTK-000', 1,0, SYSDATE, SYSDATE + 1, SYSDATE, 0);

commit;