/*========================================================
  TABLA USUARIO
========================================================*/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USUARIO_BIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUARIO (
    USER_ID VARCHAR2(20) NOT NULL,
    ID_PERSONA VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(60) ,
    ID_ROL VARCHAR2(20) NOT NULL,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_ALTA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_USUARIO PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USUARIO_PERSONA
        FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    CONSTRAINT FK_USUARIO_ROL
        FOREIGN KEY (ID_ROL) REFERENCES CAT_ROL(ID_ROL),
    CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('0', '99'))
);

COMMENT ON TABLE USUARIO IS 'Tabla de credenciales de acceso';
COMMENT ON COLUMN USUARIO.USER_ID IS 'Id único del usuario';
COMMENT ON COLUMN USUARIO.ID_PERSONA IS 'Referencia a persona';
COMMENT ON COLUMN USUARIO.PASSWORD IS 'Contraseña encriptada';
COMMENT ON COLUMN USUARIO.ID_ROL IS 'Clave del rol';
COMMENT ON COLUMN USUARIO.ESTADO IS '0=Activo, 99=Inactivo';
COMMENT ON COLUMN USUARIO.FECHA_ALTA IS 'Fecha de alta del usuario despues de la verificacion de correo';

CREATE SEQUENCE SEQ_USUARIO START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_USUARIO_ID
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        :NEW.USER_ID := 'USER-' || LPAD(SEQ_USUARIO.NEXTVAL, 6, '0');
    END IF;
END;

CREATE TABLE USUARIO_BIT (
    ID_USUARIO_BIT VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    ID_PERSONA VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(60) ,
    ID_ROL VARCHAR2(20) NOT NULL,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_ALTA DATE DEFAULT SYSDATE,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(20) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_USUARIO_BIT PRIMARY KEY (ID_USUARIO_BIT)
);

COMMENT ON TABLE USUARIO_BIT IS 'Tabla de credenciales de acceso';
COMMENT ON COLUMN USUARIO_BIT.ID_USUARIO_BIT IS 'Id unico de la tabla bitacora';
COMMENT ON COLUMN USUARIO_BIT.USER_ID IS 'Id único del usuario';
COMMENT ON COLUMN USUARIO_BIT.ID_PERSONA IS 'Referencia a persona';
COMMENT ON COLUMN USUARIO_BIT.PASSWORD IS 'Contraseña encriptada';
COMMENT ON COLUMN USUARIO_BIT.ID_ROL IS 'Clave del rol';
COMMENT ON COLUMN USUARIO_BIT.ESTADO IS '0=Activo, 99=Inactivo';
COMMENT ON COLUMN USUARIO_BIT.FECHA_ALTA IS 'Fecha de alta del usuario despues de la verificacion de correo';
COMMENT ON COLUMN USUARIO_BIT.FECHA_CREACION IS 'Fecha de insercion';
COMMENT ON COLUMN USUARIO_BIT.FECHA_MODIFICACION IS 'Fecha de ultima modificacion';
COMMENT ON COLUMN USUARIO_BIT.ACCION IS 'Accion realizada';
COMMENT ON COLUMN USUARIO_BIT.IP IS 'Direccion IP del usuario que realizo la accion';



CREATE OR REPLACE TRIGGER TRG_USUARIO_AUD
AFTER INSERT OR UPDATE ON USUARIO
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

    -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;
        -- Detectar borrado lógico
        IF :OLD.ESTADO = 0 AND :NEW.ESTADO = 99 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 99 AND :NEW.ESTADO =0 THEN
            V_ACCION := 'ACTIVATE';

        ELSE
            V_ACCION := 'UPDATE';
        END IF;

    END IF;

    INSERT INTO USUARIO_BIT ( ID_USUARIO_BIT, USER_ID, ID_PERSONA, PASSWORD, ID_ROL, ESTADO, FECHA_ALTA,
                               FECHA_CREACION , FECHA_MODIFICACION, ACCION, IP )
    VALUES (
        SYS_GUID(),
        :NEW.USER_ID,
        :NEW.ID_PERSONA,
        :NEW.PASSWORD,
        :NEW.ID_ROL,
        :NEW.ESTADO,
        :NEW.FECHA_ALTA,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_ACCION,
        FN_GET_IP
    );

END;

/*========================================================
  VISTA DE USUARIOS ACTIVOS
========================================================*/
CREATE OR REPLACE VIEW VW_USUARIOS_ACTIVOS AS
SELECT
    U.USER_ID,
    P.ID_PERSONA,
    P.NOMBRE,
    P.CORREO,
    U.PASSWORD,
    P.TELEFONO,
    R.ID_ROL,
    R.NOMBRE_ROL
FROM USUARIO U
INNER JOIN PERSONA P
    ON U.ID_PERSONA = P.ID_PERSONA
INNER JOIN CAT_ROL R
    ON U.ID_ROL = R.ID_ROL
WHERE U.ESTADO = 0
  AND P.ESTADO = 0
  AND R.ESTADO = 0
  AND P.VERIFICADO = 0;


insert into USUARIO (ID_PERSONA,PASSWORD, ID_ROL, ESTADO, FECHA_ALTA)
values ('PER-000000', '$2a$10$ADPxt2a.FjVO.1ow/PTaZ.71VBD.3CP49Fg6an7EJXlyxWTcRO9Z.','RL-001', 0, sysdate);
insert into USUARIO (ID_PERSONA,PASSWORD, ID_ROL, ESTADO, FECHA_ALTA)
values ('PER-000001', '$2a$10$ADPxt2a.FjVO.1ow/PTaZ.71VBD.3CP49Fg6an7EJXlyxWTcRO9Z.','RL-000', 0, sysdate);
commit;